import { Users, Home, ShoppingCart, Laptop, ChartLine, ArrowRightLeft } from "lucide-react";

export const CLIENT_NAV_ITEMS = [
    {
        title: "Home",
        href: "/",
    },
    { title: "About", href: "/about" },
    {
        title: "Contact Us",
        href: "/contact",
    },
];



export const adminSideBarItems = [
    {
        title: "Dashboard",
        url: "/admin",
        icon: <Home />,
    },
    {
        title: "Orders",
        url: "/admin/order",
        icon: <ShoppingCart />,
    },
    {
        title: "Customers",
        url: "/admin/customers",
        icon: <Users />,
    },
    {
        title: "Products",
        url: "/admin/products",
        icon: <Laptop />,
    },
    {
        title: "Reports",
        url: "/admin/reports",
        icon: <ChartLine />,
    },
    {
        title: "Transactions",
        url: "/admin/transactions",
        icon: <ArrowRightLeft />,
    },
];
export const REGION = [
    "Ayeyarwady",
    "Bago",
    "Chin",
    "Kachin",
    "Kayah",
    "Kayin",
    "Magway",
    "Mandalay",
    "Mon",
    "Naypyidaw",
    "Rakhine",
    "Sagaing",
    "Shan",
    "Tanintharyi",
    "Yangon",
];

export const TOWNSHIPS: Record<string, string[]> = {
    Ayeyarwady: [
        "Pathein",
        "Hinthada",
        "Bogale",
        "Myaungmya",
        "Maubin",
        "Labutta",
        "Pyapon",
    ],
    Bago: ["Bago", "Taungoo", "Pyay", "Thayarwady"],
    Chin: [
        "Hakha",
        "Falam",
        "Tedim",
        "Mindat",
        "Kanpetlet",
        "Tonzang",
        "Paletwa",
    ],
    Kachin: ["Myitkyina", "Bhamo", "Mohnyin", "Putao", "Shwegu", "Waingmaw"],
    Kayah: ["Loikaw", "Demawso", "Hpruso", "Bawlakhe", "Mese"],
    Kayin: ["Hpa-An", "Myawaddy", "Hpapun", "Kawkareik"],
    Magway: ["Magway", "Minbu", "Pakokku", "Thayet"],
    Mandalay: [
        "Amarapura",
        "Chanayethazan",
        "Chanmyathazi",
        "Mahaaungmyay",
        "Pyigyidagun",
        "Aungmyethazan",
        "Mandalay",
        "Kyaukse",
        "Myingyan",
        "Meiktila",
        "Yamethin",
    ],
    Mon: [
        "Mawlamyine",
        "Thaton",
        "Kyaikto",
        "Paung",
        "Chaungzon",
        "Mudon",
        "Thanbyuzayat",
    ],
    Naypyidaw: [
        "Zeyarthiri",
        "Pobbathiri",
        "Ottarathiri",
        "Dekkhina Thiri",
        "Pyinmana",
        "Tatkone",
        "Lewe",
        "Zabuthiri",
    ],
    Rakhine: [
        "Sittwe",
        "Kyaukphyu",
        "Maungdaw",
        "Thandwe",
        "Mrauk-U",
        "Buthidaung",
    ],
    Sagaing: ["Sagaing", "Monywa", "Shwebo", "Katha", "Kale", "Tamu"],
    Shan: ["Taunggyi", "Lashio", "Kengtung", "Muse", "Hsipaw", "Nyaungshwe"],
    Tanintharyi: ["Dawei", "Myeik", "Kawthaung"],
    Yangon: [
        "Ahlone",
        "Bahan",
        "Botataung",
        "Dagon",
        "Dagon Myothit (East)",
        "Dagon Myothit (North)",
        "Dagon Myothit (South)",
        "Dala",
        "Hlaing",
        "Hlaingthaya",
        "Insein",
        "Kamayut",
        "Kyauktada",
        "Kyimyindaing",
        "Lanmadaw",
        "Latha",
        "Mayangone",
        "Mingaladon",
        "Mingalartaungnyunt",
        "North Okkalapa",
        "Pabedan",
        "Sanchaung",
        "Seikkan",
        "South Okkalapa",
        "Tamwe",
        "Thaketa",
        "Thingangyun",
        "Yankin",
    ],
};

export const PRODUCT_CATEGORY = [
    "Laptop",
    "Processor",
    "Monitor",
    "Storage Device",
    "Printer",
    "Accessories",
    "Power Supply",
    "Desktop",
    "Networking Device",
    "Memory",
    "Desktop PC",
] as const;

export const PRODUCT_PLACEHOLDER = [
    {
        name: "Apple MacBook Pro 14-inch",
        brand: "Apple",
        category: "Laptop",
    },
    {
        name: "Microsoft Surface Studio",
        brand: "Microsoft",
        category: "Laptop",
    },
    {
        name: "G.Skill Trident Z RAM 32 GB",
        brand: "G Skill",
        category: "Processor",
    },
    {
        name: "Intel Core i7-13700 K CPU",
        brand: "Intel",
        category: "Processor",
    },
    {
        name: "HP EliteBook 840",
        brand: "HP",
        category: "Laptop",
    },
    {
        name: "LG UltraGear 27-inch",
        brand: "LG",
        category: "Monitor",
    },
    {
        name: "WD Black SN850X 1TB SSD",
        brand: "WD",
        category: "Storage Device",
    },
    {
        name: "Epson EcoTank ET-3850",
        brand: "Epson",
        category: "Printer",
    },
    {
        name: "Logitech MX Keys Keyboard",
        brand: "Logitech",
        category: "Accessories",
    },
    {
        name: "Samsung T7 Protabel SSD",
        brand: "Samsung",
        category: "Storage Device",
    },
    {
        name: "Canon Image CLASS MF644 CDW",
        brand: "Canon",
        category: "Printer",
    },
    {
        name: "APC Smart-UPS 1500VA",
        brand: "APC",
        category: "Power Supply",
    },
    {
        name: "Dell Ultrasharp Webcam",
        brand: "Dell",
        category: "Accessories",
    },
    {
        name: "HP Omen 25L",
        brand: "HP",
        category: "Desktop",
    },
    {
        name: "Asus TUF Gaming F15",
        brand: "Asus",
        category: "Laptop",
    },
    {
        name: "Seagate IronWolf 4TB HDD",
        brand: "Seagate",
        category: "Storage Device",
    },
    {
        name: "Cisco Catalyst 9200 Switch",
        brand: "Cisco",
        category: "Networking Device",
    },
    {
        name: "G.Skill Trident Z RAM 32 GB",
        brand: "G Skill",
        category: "Memory",
    },
    {
        name: "TP-link Deco XE75 Router",
        brand: "TP-link",
        category: "Networking Device",
    },
    {
        name: "Microsoft Surface Studio",
        brand: "Microsoft",
        category: "Desktop PC",
    },
    {
        name: "Acer Aspire 5",
        brand: "Acer",
        category: "Laptop",
    },
    {
        name: "HyperX Cloud Alpha Headset",
        brand: "HyperX",
        category: "Accessories",
    },
];
