export const REGION = [
    "Ayeyarwady",
    "Bago",
    "Chin",
    "Kachin",
    "Kayah",
    "Kayin",
    "Magway",
    "Mandalay",
    "Mon",
    "Naypyidaw",
    "Rakhine",
    "Sagaing",
    "Shan",
    "Tanintharyi",
    "Yangon",
];

export const TOWNSHIPS: Record<string, string[]> = {
    Ayeyarwady: [
        "Bogale - ဘိုကလေး",
        "Danubyu - ဓနုဖြူ",
        "Dedaye - ဒေးဒရဲ",
        "Einme - အိမ်မဲ",
        "Hinthada - ဟင်္သာတ",
        "Ingapu - အင်္ဂပူ",
        "Kangyidaunt - ကံကြီးတောင့်",
        "Kyaiklat - ကျိုက်လတ်",
        "Kyangin - ကြံခင်း",
        "Kyaunggon - ကျောင်းကုန်း",
        "Kyonpyaw - ကျုံပျော်",
        "Labutta - လပွတ္တာ",
        "Lemyethna - လေးမျက်နာ",
        "Maubin - မအူပင်",
        "Mawlamyinegyun - မော်လမြိုင်ကျွန်း",
        "Myaungmya - မြောင်းမြ",
        "Myanaung - မြန်အောင်",
        "Ngapudaw - ငပုတော",
        "Nyaungdon - ညောင်တုန်း",
        "Pantanaw - ပန်းတနော်",
        "Pathein - ပုသိမ်",
        "Pyapon - ဖျာပုံ",
        "Thabaung - သာပေါင်း",
        "Wakema - ဝါးခယ်မ",
        "Yegyi - ရေကြည်",
        "Zalun - ဇလွန်",
    ],
    Bago: [
        "Bago - ပဲခူး",
        "Daik-U - ဒိုက်ဦး",
        "Gyobingauk - ကြို့ပင်ကောက်",
        "Htantabin - ထန်းတပင်",
        "Kawa - ကဝ",
        "Kyaukkyi - ကျောက်ကြီး",
        "Kyauktaga - ကျောက်တံခါး",
        "Letpadan - လက်ပံတန်း",
        "Minhla - မင်းလှ",
        "Monyo - မိုးညို",
        "Nattalin - နတ်တလင်း",
        "Nyaunglebin - ညောင်လေးပင်",
        "Oktwin - အုတ်တွင်း",
        "Okpho - အုတ်ဖို",
        "Padaung - ပတောင်",
        "Paukkhaung - ပေါက်ခေါင်း",
        "Paungde - ပေါင်းတည်",
        "Phyu - ဖြူး",
        "Pyay - ပြည်",
        "Shwedaung - ရွှေတောင်",
        "Shwegyin - ရွှေကျင်",
        "Taungoo - တောင်ငူ",
        "Thanatpin - သနပ်ပင်",
        "Tharrawaddy - သာယာဝတီ",
        "Thegon - သဲကုန်း",
        "Waw - ဝေါ",
        "Yedashe - ရေတာရှည်",
        "Zigon - ဇီးကုန်း",
    ],
    Chin: [
        "Falam - ဖလမ်း",
        "Hakha - ဟားခါး",
        "Htantlang - ထန်တလန်",
        "Kanpetlet - ကန်ပက်လက်",
        "Matupi - မတူပီ",
        "Mindat - မင်းတပ်",
        "Paletwa - ပလက်ဝ",
        "Tiddim - တီးတိမ်",
        "Tonzang - တွန်းဇံ",
    ],
    Kachin: [
        "Bhamo - ဗန်းမော်",
        "Chipwi - ချီဖွေ",
        "Hpakan - ဖားကန်",
        "Injangyang - အင်ဂျန်းယန်",
        "Khaunglanhpu - ခေါင်လန်ဖူး",
        "Machanbaw - မချမ်းဘော",
        "Mansi - မန်စီ",
        "Mogaung - မိုးကောင်း",
        "Mohnyin - မိုးညှင်း",
        "Momauk - မိုးမောက်",
        "Myitkyina - မြစ်ကြီးနား",
        "Nawngmun - နောင်မွန်",
        "Puta-O - ပူတာအို",
        "Shwegu - ရွှေကူ",
        "Sumprabum - ဆွမ်ပရာဘွမ်",
        "Tanai - တနိုင်း",
        "Tsawlaw - ဆော့လော",
        "Waingmaw - ဝိုင်းမော်",
    ],
    Kayah: [
        "Bawlakhe - ဘောလခဲ",
        "Demoso - ဒီမောဆို",
        "Hpasawng - ဖားဆောင်း",
        "Hpruso - ဖရူဆို",
        "Loikaw - လွိုင်ကော်",
        "Mese - မယ်စဲ့",
        "Shadaw - ရှားတော",
    ],
    Kayin: [
        "Hlaingbwe - လှိုင်းဘွဲ",
        "Hpa-An - ဘားအံ",
        "Hpapun - ဖာပွန်",
        "Kawkareik - ကော့ကရိတ်",
        "Kyainseikgyi - ကြာအင်းဆိပ်ကြီး",
        "Myawaddy - မြဝတီ",
        "Thandaunggyi - သံတောင်ကြီး",
    ],
    Magway: [
        "Aunglan - အောင်လံ",
        "Chauk - ချောက်",
        "Gangaw - ဂန့်ဂေါ",
        "Kamma - ကမ္မ",
        "Magway - မကွေး",
        "Minbu - မင်းဘူး",
        "Mindon - မင်းတုန်း",
        "Minhla - မင်းလှ",
        "Myaing - မြိုင်",
        "Myothit - မြို့သစ်",
        "Natmauk - နတ်မောက်",
        "Ngape - ငဖဲ",
        "Pakokku - ပခုက္ကူ",
        "Pauk - ပေါက်",
        "Pwintbyu - ပွင့်ဖြူ",
        "Salin - စလင်း",
        "Saw - ဆော",
        "Seikphyu - ဆိပ်ဖြူ",
        "Sidoktaya - စေတုတ္တရာ",
        "Sinbaungwe - ဆင်ပေါင်ဝဲ",
        "Taungdwingyi - တောင်တွင်းကြီး",
        "Thayet - သရက်",
        "Tilin - ထီးလင်း",
        "Yenangyaung - ရေနံချောင်း",
        "Yesagyo - ရေစကြို",
    ],
    Mandalay: [
        "Amarapura - အမရပူရ",
        "Aungmyaythazan - အောင်မြေသာစံ",
        "Chanayethazan - ချမ်းအေးသာစံ",
        "Chanmyathazi - ချမ်းမြသာစည်",
        "Kyaukpadaung - ကျောက်ပတောင်း",
        "Kyaukse - ကျောက်ဆည်",
        "Madaya - မတ္တရာ",
        "Mahaaungmyay - မဟာအောင်မြေ",
        "Mahlaing - မလှိုင်",
        "Meiktila - မိတ္ထီလာ",
        "Mogoke - မိုးကုတ်",
        "Myingyan - မြင်းခြံ",
        "Myittha - မြစ်သား",
        "Natogyi - နွားထိုးကြီး",
        "Ngazun - ငါန်းဇွန်း",
        "Nyaung-U - ညောင်ဦး",
        "Patheingyi - ပုသိမ်ကြီး",
        "Pyawbwe - ပျော်ဘွယ်",
        "Pyigyitagon - ပြည်ကြီးတံခွန်",
        "Pyinoolwin - ပြင်ဦးလွင်",
        "Singu - စဉ့်ကူး",
        "Sintgaing - စဉ့်ကိုင်",
        "Tada-U - တံတားဦး",
        "Taungtha - တောင်သာ",
        "Thazi - သာစည်",
        "Thabeikkyin - သပိတ်ကျင်း",
        "Wundwin - ဝမ်းတွင်း",
        "Yamethin - ရမည်းသင်း",
    ],
    Mon: [
        "Billin - ဘီးလင်း",
        "Chaungzon - ချောင်းဆုံ",
        "Kyaikmaraw - ကျိုက်မရော",
        "Kyaikto - ကျိုက်ထို",
        "Mawlamyine - မော်လမြိုင်",
        "Mudon - မုဒုံ",
        "Paung - ပေါင်",
        "Thanbyuzayat - သံဖြူဇရပ်",
        "Thaton - သထုံ",
        "Ye - ရေး",
    ],
    Naypyidaw: [
        "Dekkhina Thiri - ဒက္ခိဏသီရိ",
        "Lewe - လယ်ဝေး",
        "Ottarathiri - ဥတ္တရသီရိ",
        "Pobbathiri - ပုဗ္ဗသီရိ",
        "Pyinmana - ပျဉ်းမနား",
        "Tatkone - တပ်ကုန်း",
        "Zabuthiri - ဇမ္ဗူသီရိ",
        "Zeyarthiri - ဇေယျာသီရိ",
    ],
    Rakhine: [
        "Ann - အမ်း",
        "Buthidaung - ဘူးသီးတောင်",
        "Gwa - ဂွ",
        "Kyaukpyu - ကျောက်ဖြူ",
        "Kyauktaw - ကျောက်တော်",
        "Maungdaw - မောင်းတော",
        "Minbya - မင်းပြား",
        "Mrauk-U - မြောက်ဦး",
        "Munaung - မူနောင်",
        "Myebon - မြေပုံ",
        "Pauktaw - ပေါက်တော",
        "Ponnagyun - ပုဏ္ဏားကျွန်း",
        "Ramree - ရမ်းဗြဲ",
        "Rathedaung - ရသေ့တောင်",
        "Sittwe - စစ်တွေ",
        "Thandwe - သံတွဲ",
        "Toungup - တောင်ကုတ်",
    ],
    Sagaing: [
        "Ayadaw - အရာတော်",
        "Banmauk - ဗန်းမောက်",
        "Budalin - ဘုတလင်",
        "Chaung-U - ချောင်းဦး",
        "Hkamti - ခန္တီး",
        "Homalin - ဟုမ္မလင်း",
        "Indaw - အင်းတော်",
        "Kalewa - ကလေးဝ",
        "Kale - ကလေး",
        "Kanbalu - ကန့်ဘလူ",
        "Kani - ကနီ",
        "Katha - ကသာ",
        "Kawlin - ကောလင်း",
        "Khin-U - ခင်ဦး",
        "Kyunhla - ကျွန်းလှ",
        "Lahe - လဟယ်",
        "Lay Shi - လေရှီး",
        "Mawlaik - မော်လိုက်",
        "Mingin - မင်းကင်း",
        "Mingin - မင်းကင်း",
        "Monywa - မုံရွာ",
        "Myaung - မြောင်",
        "Myinmu - မြင်းမှု",
        "Nanyun - နန်းယွန်း",
        "Pale - ပုလဲ",
        "Paungbyin - ပေါင်ပြင်",
        "Pinlebu - ပင်လယ်ဘူး",
        "Sagaing - စစ်ကိုင်း",
        "Salingyi - စလင်းကြီး",
        "Shwebo - ရွှေဘို",
        "Tabayin - ဒီပဲယင်း",
        "Tamu - တမူ",
        "Taze - တန့်ဆည်",
        "Tigyaing - ထီးချိုင့်",
        "Wetlet - ဝက်လက်",
        "Wuntho - ဝန်းသို",
        "Ye-U - ရေဦး",
        "Yinmabin - ယင်းမာပင်",
    ],
    Shan: [
        "Hseni - သိန္နီ",
        "Hsihseng - ဆီဆိုင်",
        "Hsipaw - သီပေါ",
        "Hopang - ဟိုပန်",
        "Hopong - ဟိုပုံး",
        "Kalaw - ကလော",
        "Kengtung - ကျိုင်းတုံ",
        "Konkyan - ကုန်းကြမ်း",
        "Kunhing - ကွန်ဟိန်း",
        "Kunlong - ကွမ်းလုံ",
        "Kutkai - ကွတ်ခိုင်",
        "Kyaukme - ကျောက်မဲ",
        "Kyethi - ကျေးသီး",
        "Laihka - လဲချား",
        "Langkho - လင်းခေး",
        "Lashio - လားရှိုး",
        "Laukkaing - လောက်ကိုင်",
        "Lawksawk - ရပ်စောက်",
        "Loilen - လွိုင်လင်",
        "Mabein - မဘိမ်း",
        "Manton - မန်တုံ",
        "Matman - မက်မန်း",
        "Mawkmai - မောက်မယ်",
        "Monghpyak - မိုင်းဖြတ်",
        "Monghsat - မိုင်းဆတ်",
        "Monghsu - မိုင်းရှူး",
        "Mongkaung - မိုးကောင်း",
        "Mongkhet - မိုင်းခက်",
        "Mongla - မိုင်းလား",
        "Mongmao - မိုင်းမော",
        "Mongmit - မိုးမိတ်",
        "Mongnai - မိုးနဲ",
        "Mongpan - မိုင်းပန်",
        "Mongping - မိုင်းပင်",
        "Mongton - မိုင်းတုံ",
        "Mongyang - မိုင်းယန်း",
        "Mongyai - မိုင်းရယ်",
        "Mongyawng - မိုင်းယောင်း",
        "Muse - မူဆယ်",
        "Namhkan - နမ့်ခမ်း",
        "Namhsan - နမ့်ဆန်",
        "Namphan - နမ့်ဖန်",
        "Namtu - နမ့်တူ",
        "Nansang - နမ့်ဆန်",
        "Nawnghkio - နောင်ချို",
        "Nyaungshwe - ညောင်ရွှေ",
        "Pangsang - ပန်ဆန်း",
        "Pangwaun - ပန်ဝိုင်",
        "Pekon - ဖယ်ခုံ",
        "Pindaya - ပင်းတယ",
        "Pinlaung - ပင်လောင်း",
        "Tachileik - တာချီလိတ်",
        "Tangyan - တန့်ယန်း",
        "Taunggyi - တောင်ကြီး",
        "Ywangan - ရွာငံ",
    ],
    Tanintharyi: [
        "Bokpyin - ဘုတ်ပြင်း",
        "Dawei - ထားဝယ်",
        "Kawthoung - ကော့သောင်း",
        "Kyunsu - ကျွန်းစု",
        "Launglon - လောင်းလုံ",
        "Myeik - မြိတ်",
        "Palaw - ပလော",
        "Tanintharyi - တနင်္သာရီ",
        "Thayetchaung - သရက်ချောင်း",
        "Yebyu - ရေဖြူ",
    ],
    Yangon: [
        "Ahlone - အလုံ",
        "Bahan - ဗဟန်း",
        "Botahtaung - ဗိုလ်တထောင်",
        "Cocokyun - ကိုကိုးကျွန်း",
        "Dagon - ဒဂုံ",
        "Dagon Myothit (East) - ဒဂုံမြို့သစ် (အရှေ့ပိုင်း)",
        "Dagon Myothit (North) - ဒဂုံမြို့သစ် (မြောက်ပိုင်း)",
        "Dagon Myothit (Seikkan) - ဒဂုံမြို့သစ် (ဆိပ်ကမ်း)",
        "Dagon Myothit (South) - ဒဂုံမြို့သစ် (တောင်ပိုင်း)",
        "Dala - ဒလ",
        "Dawbon - ဒေါပုံ",
        "Hlaing - လှိုင်",
        "Hlaingtharya - လှိုင်သာယာ",
        "Hlegu - လှည်းကူး",
        "Hmawbi - မှော်ဘီ",
        "Htantabin - ထန်းတပင်",
        "Insein - အင်းစိန်",
        "Kamaryut - ကမာရွတ်",
        "Kawhmu - ကော့မှူး",
        "Kayan - ကမာရွတ်",
        "Kyauktan - ကျောက်တန်",
        "Kyauktada - ကျောက်တံတား",
        "Kyeemyindaing - ကြည့်မြင်တိုင်",
        "Lanmadaw - လမ်းမတော်",
        "Latha - လသာ",
        "Mingaladon - မင်္ဂလာဒုံ",
        "Mingalartaungnyunt - မင်္ဂလာတောင်ညွန့်",
        "North Okkalapa - မြောက်ဥက္ကလာပ",
        "Pabedan - ပန်းဘဲတန်း",
        "Pazundaung - ပုဇွန်တောင်",
        "Sanchaung - စမ်းချောင်း",
        "Seikgyikanaungto - ဆိပ်ကြီးခနောင်တို",
        "Seikkan - ဆိပ်ကမ်း",
        "South Okkalapa - တောင်ဥက္ကလာပ",
        "Shwepyithar - ရွှေပြည်သာ",
        "Taikkyi - တိုက်ကြီး",
        "Tamwe - တာမွေ",
        "Thanlyin - သန်လျင်",
        "Thaketa - သာကေတ",
        "Thingangyun - သင်္ဃန်းကျွန်း",
        "Thongwa - သုံးခွ",
        "Twantay - တွံတေး",
        "Yankin - ရန်ကင်း",
    ],
};

export const PRODUCT_CATEGORY = [
    "Laptop",
    "Processor",
    "Monitor",
    "Storage Device",
    "Printer",
    "Accessories",
    "Power Supply",
    "Desktop",
    "Networking Device",
    "Memory",
    "Desktop PC",
] as const;

export const PRODUCT_PLACEHOLDER = [
    {
        name: "Apple MacBook Pro 14-inch",
        brand: "Apple",
        category: "Laptop",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074694/MacBook-Pro-Retina-14-Inch_tyxjsc.png",
    },
    {
        name: "Microsoft Surface Studio",
        brand: "Microsoft",
        category: "Laptop",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074694/Microsoft_Surface_Studio_r7jk5p.png",
    },
    {
        name: "G.Skill Trident Z RAM 32 GB",
        brand: "G Skill",
        category: "Processor",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074684/G.Skill_Trident_Z_RAM_32_GB_ycn9jy.png",
    },
    {
        name: "Intel Core i7-13700 K CPU",
        brand: "Intel",
        category: "Processor",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074683/Intel_Core_i7-13700_K_CPU_bckqat.png",
    },
    {
        name: "HP EliteBook 840",
        brand: "HP",
        category: "Laptop",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074693/HP_EliteBook_840_khoycc.png",
    },
    {
        name: "LG UltraGear 27-inch",
        brand: "LG",
        category: "Monitor",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074691/LG_UltraGear_27-inch_whtbgx.png",
    },
    {
        name: "WD Black SN850X 1TB SSD",
        brand: "WD",
        category: "Storage Device",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074695/WD_Black_SN850X_1TB_SSD_eo72xs.png",
    },
    {
        name: "Epson EcoTank ET-3850",
        brand: "Epson",
        category: "Printer",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074686/Epson_EcoTank_ET-3850_gn4kva.png",
    },
    {
        name: "Logitech MX Keys Keyboard",
        brand: "Logitech",
        category: "Accessories",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074686/Logitech_MX_Keys_Keyboard_cnzdls.png",
    },
    {
        name: "Samsung T7 Protabel SSD",
        brand: "Samsung",
        category: "Storage Device",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074942/Samsung_T7_Protabel_SSD_bffphd.png",
    },
    {
        name: "Canon Image CLASS MF644 CDW",
        brand: "Canon",
        category: "Printer",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074683/HyperX_Cloud_Alpha_Headset_qfgttb.png",
    },
    {
        name: "APC Smart-UPS 1500VA",
        brand: "APC",
        category: "Power Supply",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074682/APC_Smart-UPS_1500VA_zsb9ec.png",
    },
    {
        name: "Dell Ultrasharp Webcam",
        brand: "Dell",
        category: "Accessories",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074681/Dell_Ultrasharp_Webcam_ilykkx.png",
    },
    {
        name: "HP Omen 25L",
        brand: "HP",
        category: "Desktop",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074681/HP_Omen_25L_rvrkpn.png",
    },
    {
        name: "Asus TUF Gaming F15",
        brand: "Asus",
        category: "Laptop",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074694/Asus_TUF_Gaming_F15_b3abiq.png",
    },
    {
        name: "Seagate IronWolf 4TB HDD",
        brand: "Seagate",
        category: "Storage Device",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074681/Seagate_IronWolf_4TB_HDD_ei9erx.png",
    },
    {
        name: "Cisco Catalyst 9200 Switch",
        brand: "Cisco",
        category: "Networking Device",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074681/Cisco_Catalyst_9200_Switch_jjoo94.png",
    },
    {
        name: "G.Skill Trident Z RAM 32 GB",
        brand: "G Skill",
        category: "Memory",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074684/G.Skill_Trident_Z_RAM_32_GB_ycn9jy.png",
    },
    {
        name: "TP-link Deco XE75 Router",
        brand: "TP-link",
        category: "Networking Device",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074681/TP-link_Deco_XE75_Router_qlytjo.png",
    },
    {
        name: "Microsoft Surface Studio",
        brand: "Microsoft",
        category: "Desktop PC",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074694/Microsoft_Surface_Studio_r7jk5p.png",
    },
    {
        name: "Acer Aspire 5",
        brand: "Acer",
        category: "Laptop",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074515/Acer_Aspire_5_itwk2i.png",
    },
    {
        name: "HyperX Cloud Alpha Headset",
        brand: "HyperX",
        category: "Accessories",
        imageUrl:
            "https://res.cloudinary.com/dpvszi2rs/image/upload/v1739074683/HyperX_Cloud_Alpha_Headset_qfgttb.png",
    },
];

export const WAREHOUSES = [
    "Ullrich LLC",
    "Reichert, Murphy and Beatty",
    "Bergstrom - Turner",
    "Olson and Sons",
    "Schulist - Schamberger",
    "Kiehn, Kunze and Borer",
    "Sanford, Reichert and Olson",
    "Wintheiser and Sons",
    "Barton - Cummerata",
    "Koelpin, Hickle and Mertz",
];

export const BRAND = PRODUCT_PLACEHOLDER.map((item) => item.brand);
