export const D_Complains = [{
  "id": 1,
  "invoice_id": "78-852-6050",
  "type": "Mates",
  "status": false,
}, {
  "id": 2,
  "invoice_id": "34-553-5064",
  "type": "Allso",
  "status": true,
}, {
  "id": 3,
  "invoice_id": "69-842-0248",
  "type": "Willsmore",
  "status": true,
}, {
  "id": 4,
  "invoice_id": "71-002-4904",
  "type": "O'Rudden",
  "status": false,
}, {
  "id": 5,
  "invoice_id": "66-235-1181",
  "type": "Ninnotti",
  "status": false,
}, {
  "id": 6,
  "invoice_id": "37-120-6512",
  "type": "Dormand",
  "status": false,
}, {
  "id": 7,
  "invoice_id": "46-054-2783",
  "type": "Burg",
  "status": false,
}, {
  "id": 8,
  "invoice_id": "42-764-1795",
  "type": "Casacchia",
  "status": true,
}, {
  "id": 9,
  "invoice_id": "68-242-9202",
  "type": "Yaneev",
  "status": true,
}, {
  "id": 10,
  "invoice_id": "29-489-1748",
  "type": "La Padula",
  "status": false,
}, {
  "id": 11,
  "invoice_id": "17-245-8980",
  "type": "Marquis",
  "status": true,
}, {
  "id": 12,
  "invoice_id": "30-973-6466",
  "type": "Bagshaw",
  "status": true,
}, {
  "id": 13,
  "invoice_id": "46-385-5388",
  "type": "Fish",
  "status": true,
}, {
  "id": 14,
  "invoice_id": "79-346-0207",
  "type": "Utridge",
  "status": false,
}, {
  "id": 15,
  "invoice_id": "49-404-9170",
  "type": "Cherrie",
  "status": true,
}, {
  "id": 16,
  "invoice_id": "78-951-7866",
  "type": "Jennison",
  "status": true,
}, {
  "id": 17,
  "invoice_id": "63-411-9631",
  "type": "Tregunna",
  "status": false,
}, {
  "id": 18,
  "invoice_id": "00-431-9930",
  "type": "Joseph",
  "status": true,
}, {
  "id": 19,
  "invoice_id": "87-286-8121",
  "type": "Brehaut",
  "status": false,
}, {
  "id": 20,
  "invoice_id": "79-381-6418",
  "type": "Nelles",
  "status": false,
}, {
  "id": 21,
  "invoice_id": "25-066-1848",
  "type": "Hyndley",
  "status": true,
}, {
  "id": 22,
  "invoice_id": "93-551-8472",
  "type": "Berge",
  "status": true,
}, {
  "id": 23,
  "invoice_id": "82-042-3436",
  "type": "Jaan",
  "status": false,
}, {
  "id": 24,
  "invoice_id": "96-295-8341",
  "type": "Peppard",
  "status": true,
}, {
  "id": 25,
  "invoice_id": "62-690-3386",
  "type": "Skeffington",
  "status": true,
}, {
  "id": 26,
  "invoice_id": "83-072-9145",
  "type": "Tumulty",
  "status": false,
}, {
  "id": 27,
  "invoice_id": "52-819-0462",
  "type": "Runcie",
  "status": true,
}, {
  "id": 28,
  "invoice_id": "15-646-2557",
  "type": "Windle",
  "status": false,
}, {
  "id": 29,
  "invoice_id": "74-285-4661",
  "type": "Burman",
  "status": true,
}, {
  "id": 30,
  "invoice_id": "85-230-4123",
  "type": "Wyldes",
  "status": true,
}, {
  "id": 31,
  "invoice_id": "69-873-0687",
  "type": "Dumingo",
  "status": true,
}, {
  "id": 32,
  "invoice_id": "13-652-5246",
  "type": "Garrity",
  "status": true,
}, {
  "id": 33,
  "invoice_id": "92-248-8462",
  "type": "Hopkynson",
  "status": false,
}, {
  "id": 34,
  "invoice_id": "61-776-0502",
  "type": "Merit",
  "status": false,
}, {
  "id": 35,
  "invoice_id": "88-190-8961",
  "type": "Trask",
  "status": false,
}, {
  "id": 36,
  "invoice_id": "23-603-1669",
  "type": "Josefovic",
  "status": false,
}, {
  "id": 37,
  "invoice_id": "89-203-7320",
  "type": "Nunes Nabarro",
  "status": true,
}, {
  "id": 38,
  "invoice_id": "75-180-0536",
  "type": "Whitely",
  "status": false,
}, {
  "id": 39,
  "invoice_id": "54-281-5616",
  "type": "Rotge",
  "status": true,
}, {
  "id": 40,
  "invoice_id": "72-287-1284",
  "type": "Brougham",
  "status": true,
}, {
  "id": 41,
  "invoice_id": "92-639-9050",
  "type": "McCoish",
  "status": false,
}, {
  "id": 42,
  "invoice_id": "27-888-2112",
  "type": "Klimentyev",
  "status": true,
}, {
  "id": 43,
  "invoice_id": "67-449-1668",
  "type": "Beadle",
  "status": false,
}, {
  "id": 44,
  "invoice_id": "09-273-2083",
  "type": "Fletham",
  "status": false,
}, {
  "id": 45,
  "invoice_id": "88-671-4667",
  "type": "Vassie",
  "status": true,
}, {
  "id": 46,
  "invoice_id": "71-958-3772",
  "type": "Filippazzo",
  "status": true,
}, {
  "id": 47,
  "invoice_id": "41-510-8619",
  "type": "Esche",
  "status": false,
}, {
  "id": 48,
  "invoice_id": "66-022-8281",
  "type": "Giovanetti",
  "status": true,
}, {
  "id": 49,
  "invoice_id": "79-276-9190",
  "type": "Scalera",
  "status": true,
}, {
  "id": 50,
  "invoice_id": "35-693-3212",
  "type": "Elsie",
  "status": true,
}];

export const D_Orders = [{
  "id": 1,
  "user_id": "ZS7PM",
  "order_date": "2/22/2024",
  "order_status": true,
  "total_amount": 3,
}, {
  "id": 2,
  "user_id": "D6NKX",
  "order_date": "5/4/2024",
  "order_status": true,
  "total_amount": 2,
}, {
  "id": 3,
  "user_id": "YN1FS",
  "order_date": "1/23/2025",
  "order_status": false,
  "total_amount": 7,
}, {
  "id": 4,
  "user_id": "3BMFZ",
  "order_date": "7/17/2024",
  "order_status": false,
  "total_amount": 4,
}, {
  "id": 5,
  "user_id": "Z3K96",
  "order_date": "5/7/2024",
  "order_status": true,
  "total_amount": 5,
}, {
  "id": 6,
  "user_id": "YQXNM",
  "order_date": "11/20/2024",
  "order_status": false,
  "total_amount": 10,
}, {
  "id": 7,
  "user_id": "JPYYS",
  "order_date": "8/19/2024",
  "order_status": true,
  "total_amount": 6,
}, {
  "id": 8,
  "user_id": "Q621M",
  "order_date": "12/9/2024",
  "order_status": false,
  "total_amount": 1,
}, {
  "id": 9,
  "user_id": "Y1EF0",
  "order_date": "10/10/2024",
  "order_status": false,
  "total_amount": 1,
}, {
  "id": 10,
  "user_id": "JW5JK",
  "order_date": "8/3/2024",
  "order_status": false,
  "total_amount": 4,
}, {
  "id": 11,
  "user_id": "GG2YP",
  "order_date": "1/28/2025",
  "order_status": true,
  "total_amount": 4,
}, {
  "id": 12,
  "user_id": "R38RR",
  "order_date": "8/4/2024",
  "order_status": true,
  "total_amount": 10,
}, {
  "id": 13,
  "user_id": "GZ5B9",
  "order_date": "1/10/2025",
  "order_status": false,
  "total_amount": 4,
}, {
  "id": 14,
  "user_id": "CAXDS",
  "order_date": "2/23/2024",
  "order_status": false,
  "total_amount": 4,
}, {
  "id": 15,
  "user_id": "071YC",
  "order_date": "8/11/2024",
  "order_status": true,
  "total_amount": 9,
}, {
  "id": 16,
  "user_id": "PQB1D",
  "order_date": "5/5/2024",
  "order_status": true,
  "total_amount": 6,
}, {
  "id": 17,
  "user_id": "MVZ7W",
  "order_date": "5/7/2024",
  "order_status": false,
  "total_amount": 9,
}, {
  "id": 18,
  "user_id": "ZBZ6X",
  "order_date": "11/28/2024",
  "order_status": false,
  "total_amount": 1,
}, {
  "id": 19,
  "user_id": "H9X16",
  "order_date": "2/22/2024",
  "order_status": true,
  "total_amount": 1,
}, {
  "id": 20,
  "user_id": "Y86JV",
  "order_date": "1/4/2025",
  "order_status": true,
  "total_amount": 10,
}, {
  "id": 21,
  "user_id": "GMYKV",
  "order_date": "11/9/2024",
  "order_status": false,
  "total_amount": 8,
}, {
  "id": 22,
  "user_id": "98G44",
  "order_date": "5/29/2024",
  "order_status": false,
  "total_amount": 1,
}, {
  "id": 23,
  "user_id": "F0XC4",
  "order_date": "8/11/2024",
  "order_status": false,
  "total_amount": 10,
}, {
  "id": 24,
  "user_id": "9YD9G",
  "order_date": "12/23/2024",
  "order_status": false,
  "total_amount": 7,
}, {
  "id": 25,
  "user_id": "SAHHA",
  "order_date": "5/9/2024",
  "order_status": true,
  "total_amount": 5,
}, {
  "id": 26,
  "user_id": "D7E0E",
  "order_date": "4/18/2024",
  "order_status": false,
  "total_amount": 10,
}, {
  "id": 27,
  "user_id": "M64EK",
  "order_date": "5/17/2024",
  "order_status": true,
  "total_amount": 6,
}, {
  "id": 28,
  "user_id": "F16QR",
  "order_date": "4/24/2024",
  "order_status": false,
  "total_amount": 7,
}, {
  "id": 29,
  "user_id": "4BDCN",
  "order_date": "5/26/2024",
  "order_status": true,
  "total_amount": 7,
}, {
  "id": 30,
  "user_id": "S2V77",
  "order_date": "9/19/2024",
  "order_status": false,
  "total_amount": 8,
}, {
  "id": 31,
  "user_id": "M0KTV",
  "order_date": "9/18/2024",
  "order_status": false,
  "total_amount": 1,
}, {
  "id": 32,
  "user_id": "PGZ29",
  "order_date": "3/16/2024",
  "order_status": false,
  "total_amount": 7,
}, {
  "id": 33,
  "user_id": "08FAF",
  "order_date": "7/25/2024",
  "order_status": false,
  "total_amount": 1,
}, {
  "id": 34,
  "user_id": "T3MVY",
  "order_date": "1/10/2025",
  "order_status": false,
  "total_amount": 2,
}, {
  "id": 35,
  "user_id": "9XVEF",
  "order_date": "2/16/2024",
  "order_status": false,
  "total_amount": 5,
}, {
  "id": 36,
  "user_id": "0GAK2",
  "order_date": "8/1/2024",
  "order_status": false,
  "total_amount": 10,
}, {
  "id": 37,
  "user_id": "C8B1B",
  "order_date": "10/2/2024",
  "order_status": true,
  "total_amount": 6,
}, {
  "id": 38,
  "user_id": "QCGRR",
  "order_date": "2/21/2024",
  "order_status": true,
  "total_amount": 5,
}, {
  "id": 39,
  "user_id": "ZK4HG",
  "order_date": "10/26/2024",
  "order_status": false,
  "total_amount": 5,
}, {
  "id": 40,
  "user_id": "8S23V",
  "order_date": "10/15/2024",
  "order_status": false,
  "total_amount": 3,
}, {
  "id": 41,
  "user_id": "9K026",
  "order_date": "9/20/2024",
  "order_status": true,
  "total_amount": 2,
}, {
  "id": 42,
  "user_id": "ETQQF",
  "order_date": "7/9/2024",
  "order_status": true,
  "total_amount": 8,
}, {
  "id": 43,
  "user_id": "R13XQ",
  "order_date": "4/13/2024",
  "order_status": false,
  "total_amount": 10,
}, {
  "id": 44,
  "user_id": "7W9F9",
  "order_date": "4/19/2024",
  "order_status": false,
  "total_amount": 7,
}, {
  "id": 45,
  "user_id": "ER1H0",
  "order_date": "6/7/2024",
  "order_status": true,
  "total_amount": 2,
}, {
  "id": 46,
  "user_id": "FEW8P",
  "order_date": "3/5/2024",
  "order_status": true,
  "total_amount": 4,
}, {
  "id": 47,
  "user_id": "KGEHR",
  "order_date": "3/27/2024",
  "order_status": false,
  "total_amount": 2,
}, {
  "id": 48,
  "user_id": "FD0GY",
  "order_date": "7/19/2024",
  "order_status": true,
  "total_amount": 10,
}, {
  "id": 49,
  "user_id": "9STGX",
  "order_date": "4/15/2024",
  "order_status": true,
  "total_amount": 5,
}, {
  "id": 50,
  "user_id": "V1A51",
  "order_date": "5/26/2024",
  "order_status": true,
  "total_amount": 2,
}];

export const D_Users = [{
  "id": 1,
  "name": "Cristobal Kingzett",
  "password": "$2a$04$Ie1ySDfcxaWGBk0oOMrH2uqDOKY8HxDB0xv6BrdllzQnJHCIpDnmq",
  "email": "ckingzett0@moonfruit.com",
  "phone": "881-781-0909",
  "address": "79 Grover Parkway",
  "township": "Pabedan",
  "region": "Bago",
  "role": "shop",
}, {
  "id": 2,
  "name": "Feliza Ondrus",
  "password": "$2a$04$mtjL0Ln2gtquK8zdP0Re0eSOE8dImObALQtvQ8w9FbvybHNB4CIHy",
  "email": "fondrus1@samsung.com",
  "phone": "305-150-2123",
  "address": "9 Elmside Point",
  "township": "TaungNyunt",
  "region": "Shan",
  "role": "user",
}, {
  "id": 3,
  "name": "Keelia Strelitz",
  "password": "$2a$04$meT.mda2bR1CsTbdRrROU.UUdh7rqVCVLEuk9YbzIifW2tMYlTJ3S",
  "email": "kstrelitz2@ebay.com",
  "phone": "200-394-0317",
  "address": "698 Dayton Parkway",
  "township": "Thaketa",
  "region": "Shan",
  "role": "user",
}, {
  "id": 4,
  "name": "Obediah Keywood",
  "password": "$2a$04$yX42HbCucQDJ4elayqnI3OWvNjLdPgvOCLHN/hQqXdlfiLWD/.fKW",
  "email": "okeywood3@goo.ne.jp",
  "phone": "696-872-5071",
  "address": "6253 Crownhardt Hill",
  "township": "Thaketa",
  "region": "Mon",
  "role": "shop",
}, {
  "id": 5,
  "name": "Barbabas Skelton",
  "password": "$2a$04$VcBkzIeNH2yES1mIrw5Nc./FkLuX7PRW.CW0y2MpCv6NpoACwwxI2",
  "email": "bskelton4@businessweek.com",
  "phone": "572-196-8184",
  "address": "2 Arapahoe Trail",
  "township": "Bahan",
  "region": "Magway",
  "role": "shop",
}, {
  "id": 6,
  "name": "Rina Fells",
  "password": "$2a$04$MPVd4dHPbTp6an0nYs2gu.qahX.NsIwaFgaHCnWOD0Cz4WLqfgJ72",
  "email": "rfells5@clickbank.net",
  "phone": "771-416-3734",
  "address": "6 Southridge Point",
  "township": "Pabedan",
  "region": "Mon",
  "role": "user",
}, {
  "id": 7,
  "name": "Bernardine Bent",
  "password": "$2a$04$UuHWdLw9wgWi5Oym/pwXFeNtcc6RyGbPDXAIvwVIRg0wRJIsEanKq",
  "email": "bbent6@pagesperso-orange.fr",
  "phone": "582-512-5153",
  "address": "56524 Eastwood Point",
  "township": "Sanchaung",
  "region": "Magway",
  "role": "shop",
}, {
  "id": 8,
  "name": "Nert Minifie",
  "password": "$2a$04$awN3uLjJZCKh4kzjOvdOoeuhiF.HcP1MgKlYJkUCX3Q9QQ8zuJIqm",
  "email": "nminifie7@g.co",
  "phone": "896-610-6457",
  "address": "15812 Longview Way",
  "township": "Thaketa",
  "region": "Mon",
  "role": "user",
}, {
  "id": 9,
  "name": "Halsey Gillhespy",
  "password": "$2a$04$w9K99rc0J15IfvdSCAVbeOT/.ca.GXfTtBRiAmhXXraNTaVZoVxzC",
  "email": "hgillhespy8@liveinternet.ru",
  "phone": "226-432-3183",
  "address": "6 Bluestem Hill",
  "township": "Tamwe",
  "region": "Bago",
  "role": "shop",
}, {
  "id": 10,
  "name": "Paulie Mendenhall",
  "password": "$2a$04$UzybxpFAKLKI4xY/7J6Ew.MSXkf.1XGwIm/dSBBjNmL3f.24Rh5Dm",
  "email": "pmendenhall9@miibeian.gov.cn",
  "phone": "842-493-7755",
  "address": "34 Forest Lane",
  "township": "Bahan",
  "region": "Bago",
  "role": "user",
}, {
  "id": 11,
  "name": "Felecia Quinn",
  "password": "$2a$04$PHcZyRo/FjmXUAW8DMKXCOQg9cGpsCytlu1FbGjWLPhSXPB6okG1q",
  "email": "fquinna@sitemeter.com",
  "phone": "529-551-8667",
  "address": "541 Burrows Circle",
  "township": "TaungNyunt",
  "region": "Ayeyarwaddy",
  "role": "shop",
}, {
  "id": 12,
  "name": "Benedick Jossum",
  "password": "$2a$04$Qeku/ph5/.CMoG5lKtoda..7zQ2EDM2PSAdIY.qk4EHE0KAydre5m",
  "email": "bjossumb@answers.com",
  "phone": "479-296-2180",
  "address": "699 Heffernan Lane",
  "township": "Hlaing",
  "region": "",
  "role": "user",
}, {
  "id": 13,
  "name": "Jandy Laingmaid",
  "password": "$2a$04$Z3PgmfWVPpEsS7FGK5OywuWbiWil1Yuk.sCp0aQZsV8rPjGd/KkRG",
  "email": "jlaingmaidc@eventbrite.com",
  "phone": "659-851-7394",
  "address": "4 Prairie Rose Park",
  "township": "Thaketa",
  "region": "Magway",
  "role": "user",
}, {
  "id": 14,
  "name": "Juliann Alfonsetti",
  "password": "$2a$04$Gum5.84sW7OPnfXVVlpdJeBT118SjrfkCUowHOWula/gRgiilQQ7W",
  "email": "jalfonsettid@acquirethisname.com",
  "phone": "625-466-6871",
  "address": "302 Crescent Oaks Avenue",
  "township": "Sanchaung",
  "region": "",
  "role": "user",
}, {
  "id": 15,
  "name": "Randy Coonan",
  "password": "$2a$04$DBuoG3LYdCMVc85cGc3ro.gIzXE.9ZIKSWEo3ITcudjlFfOLgpXT.",
  "email": "rcoonane@washington.edu",
  "phone": "513-877-1108",
  "address": "4 Vahlen Point",
  "township": "Bahan",
  "region": "Mon",
  "role": "shop",
}, {
  "id": 16,
  "name": "Jens Tankard",
  "password": "$2a$04$HYsTzNUDOjyWb8L6mJHJ5u.C2DgMYBWCFN6uqhX.fjiYaWR29uIzO",
  "email": "jtankardf@ocn.ne.jp",
  "phone": "702-296-9578",
  "address": "79780 Pawling Park",
  "township": "Hlaing",
  "region": "Bago",
  "role": "user",
}, {
  "id": 17,
  "name": "Trish Vakhonin",
  "password": "$2a$04$qRWLF.C/G2CMeGZpV.K2L.UqnEcvxysmS7hHZy4G/SK3i61aoEyla",
  "email": "tvakhoning@is.gd",
  "phone": "816-303-4579",
  "address": "7 Holy Cross Avenue",
  "township": "TaungNyunt",
  "region": "Bago",
  "role": "shop",
}, {
  "id": 18,
  "name": "Melany Harrowsmith",
  "password": "$2a$04$.8nwMspXlWPNH4rrMQ527uGuDXfg7vTQFW7kE4g0dMfVTw5WwIV6O",
  "email": "mharrowsmithh@thetimes.co.uk",
  "phone": "599-237-2228",
  "address": "56 Russell Hill",
  "township": "Sanchaung",
  "region": "Ayeyarwaddy",
  "role": "shop",
}, {
  "id": 19,
  "name": "Kippie Deyes",
  "password": "$2a$04$PA1ecoaGyw18qQVSuOWWMOjB2BLhXOAEjuLHSMsaMigtZNWa2q7Yq",
  "email": "kdeyesi@miibeian.gov.cn",
  "phone": "366-322-4511",
  "address": "514 Union Crossing",
  "township": "Hlaing",
  "region": "Yangon",
  "role": "user",
}, {
  "id": 20,
  "name": "Sena Hazeldine",
  "password": "$2a$04$KfzTxE2adsu5sAaMZe5Tgu98Qhp9fPTtsdnstodAsbLpZNFZhcCEG",
  "email": "shazeldinej@plala.or.jp",
  "phone": "202-920-1744",
  "address": "35 Karstens Drive",
  "township": "Sanchaung",
  "region": "Magway",
  "role": "shop",
}, {
  "id": 21,
  "name": "Sandy Fibbit",
  "password": "$2a$04$B7uAHwod6tExUn61ShehJe8CGTCfzLzMYAHccfFNGCOExywOmHrS6",
  "email": "sfibbitk@cisco.com",
  "phone": "954-828-7528",
  "address": "3216 Hintze Point",
  "township": "Sanchaung",
  "region": "Bago",
  "role": "shop",
}, {
  "id": 22,
  "name": "Lurleen Roiz",
  "password": "$2a$04$FcSouQXvj6XBtFYtRZpfUeg8mNFkOIzd.c1INaxO.ITdhGKCWVpx.",
  "email": "lroizl@elpais.com",
  "phone": "579-710-5827",
  "address": "431 Burning Wood Place",
  "township": "Tamwe",
  "region": "Shan",
  "role": "user",
}, {
  "id": 23,
  "name": "Wolfgang Blockwell",
  "password": "$2a$04$lqCDqN5gzWzQ3/K83.opZ.iL5NAEG7TnBcr3.5vz8VTsAGpIoNpdC",
  "email": "wblockwellm@last.fm",
  "phone": "295-298-1504",
  "address": "93126 Prairie Rose Way",
  "township": "Hlaing",
  "region": "Bago",
  "role": "user",
}, {
  "id": 24,
  "name": "Etan Kirwin",
  "password": "$2a$04$lpI6gaE97FuXApMXbXJleeIYQGJyuz9jV9WxHUfKKAMQImvjCdcnq",
  "email": "ekirwinn@vinaora.com",
  "phone": "608-509-1277",
  "address": "1651 Garrison Center",
  "township": "Sanchaung",
  "region": "Ayeyarwaddy",
  "role": "shop",
}, {
  "id": 25,
  "name": "Ernesto Antat",
  "password": "$2a$04$kJcZE2Rj7NJFJ3Pww1po3uKjzRW95C0lQ16qlHleLtF23yVSaJcDe",
  "email": "eantato@springer.com",
  "phone": "272-983-0079",
  "address": "43076 Paget Terrace",
  "township": "Thaketa",
  "region": "Ayeyarwaddy",
  "role": "user",
}, {
  "id": 26,
  "name": "Vallie Zwicker",
  "password": "$2a$04$PzEt3LQ7Gbs7qymBw2GbrOryKanWRLUxZsOuOFSh7urWUPeolvRNu",
  "email": "vzwickerp@163.com",
  "phone": "604-573-9013",
  "address": "69832 Sunfield Circle",
  "township": "Bahan",
  "region": "Bago",
  "role": "user",
}, {
  "id": 27,
  "name": "Jedidiah Kersley",
  "password": "$2a$04$D0DMgf.rdGD7NEOQpNHC..P7BoV681..2J2JxlZ88MG8YRf4N1hWu",
  "email": "jkersleyq@dailymotion.com",
  "phone": "242-542-7392",
  "address": "83 Knutson Alley",
  "township": "Bahan",
  "region": "Magway",
  "role": "user",
}, {
  "id": 28,
  "name": "Aldric Heining",
  "password": "$2a$04$kkQ7XfdR.ayCsRVCOVXs4OQjTQk6uQFmagihNSvmKnBwCOzZWPyc6",
  "email": "aheiningr@51.la",
  "phone": "604-776-0875",
  "address": "74 Oriole Way",
  "township": "Insein",
  "region": "Ayeyarwaddy",
  "role": "user",
}, {
  "id": 29,
  "name": "Terri-jo Michele",
  "password": "$2a$04$oCUdvjDomOKdpO7/loOjU.Uiko1vpk2VFu/FVyJXK0OjUt71CUZrO",
  "email": "tmicheles@samsung.com",
  "phone": "746-583-2437",
  "address": "3 Hanson Road",
  "township": "Thaketa",
  "region": "Ayeyarwaddy",
  "role": "user",
}, {
  "id": 30,
  "name": "Aeriel Oliveras",
  "password": "$2a$04$9wuof7SuRj29NZ9.pKOqbO9Af2nQiuOgrdptJ2enyk9AdlO1eZYE6",
  "email": "aoliverast@i2i.jp",
  "phone": "840-570-6151",
  "address": "31 Daystar Avenue",
  "township": "Tamwe",
  "region": "Ayeyarwaddy",
  "role": "user",
}, {
  "id": 31,
  "name": "Bord Relf",
  "password": "$2a$04$/cJCou9fw0aZvPTxFmQr5edwc4rF5/nsSnriIEPLrPw81ITwXPCQ2",
  "email": "brelfu@hugedomains.com",
  "phone": "450-952-2333",
  "address": "516 John Wall Lane",
  "township": "Pabedan",
  "region": "Yangon",
  "role": "user",
}, {
  "id": 32,
  "name": "Ursula Hyett",
  "password": "$2a$04$9ztSJfR6ZsE/.C1Q3/qi0.VP.qs5qb4zJDVjKjGKbT1N0jmPcOC0y",
  "email": "uhyettv@microsoft.com",
  "phone": "958-198-7564",
  "address": "85727 Calypso Street",
  "township": "Bahan",
  "region": "Mon",
  "role": "user",
}, {
  "id": 33,
  "name": "Merilyn Roelofs",
  "password": "$2a$04$EI2fSFyk8HGSaW0tKmRyOeyOeMeU/2dbgLKuo66RtsTOUmlr4yppK",
  "email": "mroelofsw@mtv.com",
  "phone": "231-849-5240",
  "address": "39025 Moose Pass",
  "township": "TaungNyunt",
  "region": "Bago",
  "role": "user",
}, {
  "id": 34,
  "name": "Sean Speeks",
  "password": "$2a$04$JmSGF/1avqHQjZtiPqjIfOpHc6AxiA/DK9y/62CvxLq5UkQRvV70O",
  "email": "sspeeksx@list-manage.com",
  "phone": "300-790-8185",
  "address": "070 Marquette Plaza",
  "township": "Insein",
  "region": "Mon",
  "role": "user",
}, {
  "id": 35,
  "name": "Myrlene Verlander",
  "password": "$2a$04$Mfmg4lXpdrNCmQmui5LdYeesUfyi3Xs5aqf3ZP/.7sLDfGNSQiw8.",
  "email": "mverlandery@epa.gov",
  "phone": "980-563-0200",
  "address": "60 Cherokee Parkway",
  "township": "Pabedan",
  "region": "Yangon",
  "role": "shop",
}, {
  "id": 36,
  "name": "Robbie Mullan",
  "password": "$2a$04$T9gWu3s3OdzLGcx/qv6F3ejmPUdqejwqSIktncluAGDPRUFlPhyXy",
  "email": "rmullanz@phoca.cz",
  "phone": "262-443-2169",
  "address": "90945 Thompson Drive",
  "township": "Tamwe",
  "region": "Shan",
  "role": "shop",
}, {
  "id": 37,
  "name": "Parke Goggins",
  "password": "$2a$04$xgUgjwtj3rzsaL737f3FNuL/ybXpZn9QqbxTzZZF4vXXQWMJgi2bO",
  "email": "pgoggins10@epa.gov",
  "phone": "380-621-0172",
  "address": "504 Ludington Street",
  "township": "TaungNyunt",
  "region": "Bago",
  "role": "user",
}, {
  "id": 38,
  "name": "Emerson Wraighte",
  "password": "$2a$04$bJzf7LH83i3xa9YSS2bWLOd18FG9cYGhv25X7fHEiPQMBhCOFYdiG",
  "email": "ewraighte11@goodreads.com",
  "phone": "859-303-7781",
  "address": "10856 South Center",
  "township": "Tamwe",
  "region": "Ayeyarwaddy",
  "role": "shop",
}, {
  "id": 39,
  "name": "Kimball Gotcliff",
  "password": "$2a$04$7DJSFiCjKjOiHGVib/vC6.utEobOSJd.aN4xi8SxhSPZJ5o8.OEQe",
  "email": "kgotcliff12@ft.com",
  "phone": "985-994-6601",
  "address": "781 Corry Road",
  "township": "TaungNyunt",
  "region": "Bago",
  "role": "user",
}, {
  "id": 40,
  "name": "Madel Meenehan",
  "password": "$2a$04$89QsoX9MIIn4pnTpSl6j9.DVrN7PW88gYYyfm38aRrNgzSPeFTLWO",
  "email": "mmeenehan13@answers.com",
  "phone": "652-734-4711",
  "address": "41323 Fairview Parkway",
  "township": "TaungNyunt",
  "region": "Bago",
  "role": "user",
}, {
  "id": 41,
  "name": "Lanae Lesaunier",
  "password": "$2a$04$J550N3FrV8YvKiPMriyvFu0iZSsOuHXsVytXZYKKY3YvFXrE426Wy",
  "email": "llesaunier14@nationalgeographic.com",
  "phone": "440-497-8812",
  "address": "0 Dryden Plaza",
  "township": "Hlaing",
  "region": "Bago",
  "role": "user",
}, {
  "id": 42,
  "name": "Davidson Pott",
  "password": "$2a$04$7dPNvlrxF5Pl/.fPkqWjcuMVb2GBTnHcMJ2WnhJXzhuzTpAIhJsF.",
  "email": "dpott15@histats.com",
  "phone": "104-874-5935",
  "address": "488 Pearson Way",
  "township": "Sanchaung",
  "region": "Mon",
  "role": "shop",
}, {
  "id": 43,
  "name": "Yanaton Bucher",
  "password": "$2a$04$hOrbqJr2pD/6DjPY9OMhj.r3wOqTL7jMEj6dAgelzy7anGYLc7xw2",
  "email": "ybucher16@google.com.hk",
  "phone": "239-384-6256",
  "address": "2 Mitchell Point",
  "township": "Insein",
  "region": "",
  "role": "shop",
}, {
  "id": 44,
  "name": "Merla Kemwal",
  "password": "$2a$04$6FVYvYwtLHClbrVV9nRve.pFZulViUs/2X1vXW5zb.v7VOCjcb8CK",
  "email": "mkemwal17@parallels.com",
  "phone": "428-203-9820",
  "address": "872 Pond Crossing",
  "township": "Thaketa",
  "region": "",
  "role": "shop",
}, {
  "id": 45,
  "name": "Kania Cheng",
  "password": "$2a$04$sKmHSEMkfylnr35fC6.wgOe7hQplIPGTCf2yQuxiEY/oYRcChKe5m",
  "email": "kcheng18@cornell.edu",
  "phone": "873-699-5288",
  "address": "477 Redwing Terrace",
  "township": "Bahan",
  "region": "Magway",
  "role": "user",
}, {
  "id": 46,
  "name": "Xever Kemster",
  "password": "$2a$04$JbIfln628osdjQOIUI3Bi.tmpsvXoVUw7t/FX3vaqbeY0pW2DkaCy",
  "email": "xkemster19@diigo.com",
  "phone": "407-264-8799",
  "address": "44695 Continental Park",
  "township": "Bahan",
  "region": "Magway",
  "role": "user",
}, {
  "id": 47,
  "name": "Gus Myhan",
  "password": "$2a$04$Gr3cLY/zpzoTp4HMJyuPVe5i84DFlVE4uSYCUhpzjkm/ffG6mVpKm",
  "email": "gmyhan1a@macromedia.com",
  "phone": "670-390-8692",
  "address": "29 Muir Way",
  "township": "Thaketa",
  "region": "",
  "role": "user",
}, {
  "id": 48,
  "name": "Ethelred Gammel",
  "password": "$2a$04$gHRgJ/EZvDRdwzmW0ixTje3pO2HgAfN4k.wCCtRpsUEU7cMqRUO/K",
  "email": "egammel1b@sina.com.cn",
  "phone": "870-953-1974",
  "address": "93 Mesta Alley",
  "township": "Bahan",
  "region": "Mon",
  "role": "user",
}, {
  "id": 49,
  "name": "Dionysus Croxall",
  "password": "$2a$04$PJKCMLTGC2KuKBbhkS4PCOA2X/zxMODaQmWtIkqZaxnNUVKcRJNxO",
  "email": "dcroxall1c@mail.ru",
  "phone": "428-740-8099",
  "address": "7487 Tomscot Junction",
  "township": "Pabedan",
  "region": "Yangon",
  "role": "user",
}, {
  "id": 50,
  "name": "Grissel Geillier",
  "password": "$2a$04$wjivI/wJC.yTflj9HjPG4ekAtT3g8KT2AFQnrluVzb67KsJnXkIcm",
  "email": "ggeillier1d@joomla.org",
  "phone": "793-733-2401",
  "address": "9 Eagan Court",
  "township": "Insein",
  "region": "Mon",
  "role": "user",
}];

export const D_ProductDetails = [{
  "id": 1,
  "name": "NIU Z10",
  "category": "laptop",
  "brand": "MSI",
  "price": 97.31,
  "description": "Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.",
  "discount": 0.05,
  "warehouse_id": "e9eb1a51-78a3-41e1-831b-80b66bc4727f",
}, {
  "id": 2,
  "name": "Samsung S5330 Wave533",
  "category": "printer",
  "brand": "MSI",
  "price": 64.19,
  "description": "Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.",
  "discount": 0.57,
  "warehouse_id": "e0c69e15-b5e7-4376-8e85-87a6868e0d33",
}, {
  "id": 3,
  "name": "Nokia C3-01 Touch and Type",
  "category": "accessories",
  "brand": "Mac",
  "price": 53.73,
  "description": "Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.",
  "discount": 0.68,
  "warehouse_id": "5fd1efab-bf72-4692-8a74-c661e24becaf",
}, {
  "id": 4,
  "name": "LG Q31",
  "category": "accessories",
  "brand": "Dell",
  "price": 56.85,
  "description": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.",
  "discount": 0.3,
  "warehouse_id": "597fa1da-d2f9-419c-84f0-2816061ea1f6",
}, {
  "id": 5,
  "name": "ZTE Blade Q Maxi",
  "category": "projector",
  "brand": "Epson",
  "price": 105.36,
  "description": "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.",
  "discount": 0.45,
  "warehouse_id": "91e9cdd1-5e22-46df-b004-028f09e71a99",
}, {
  "id": 6,
  "name": "Sony Ericsson W600",
  "category": "desktop",
  "brand": "",
  "price": 93.16,
  "description": "Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.",
  "discount": 0.66,
  "warehouse_id": "73164cdb-aa75-4709-8e3f-3d35c7afb6ea",
}, {
  "id": 7,
  "name": "HTC Desire 20 Pro",
  "category": "accessories",
  "brand": "",
  "price": 50.15,
  "description": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.",
  "discount": 0.09,
  "warehouse_id": "9f99d03b-7211-4543-a59f-6065ef2d6684",
}, {
  "id": 8,
  "name": "Wiko Y80",
  "category": "printer",
  "brand": "Mac",
  "price": 108.87,
  "description": "Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
  "discount": 0.33,
  "warehouse_id": "1cf380d7-8e1b-4b89-9419-61d918b9d613",
}, {
  "id": 9,
  "name": "Asus Zenfone Pegasus 3",
  "category": "memory",
  "brand": "Toyota",
  "price": 63.1,
  "description": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.",
  "discount": 0.35,
  "warehouse_id": "32f1060f-c5cb-4c0c-b304-5e006abb8fdf",
}, {
  "id": 10,
  "name": "Oppo A12s",
  "category": "desktop",
  "brand": "Toyota",
  "price": 59.65,
  "description": "Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.",
  "discount": 0.76,
  "warehouse_id": "3cebd6ae-1623-46e0-8573-cba9301295b4",
}, {
  "id": 11,
  "name": "Archos 55b Cobalt",
  "category": "accessories",
  "brand": "Lenovo",
  "price": 34.95,
  "description": "In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
  "discount": 0.73,
  "warehouse_id": "0ccb5c5c-e454-4ce7-b7da-94e20506747b",
}, {
  "id": 12,
  "name": "BQ  Aquaris M10",
  "category": "memory",
  "brand": "MSI",
  "price": 86.91,
  "description": "Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.",
  "discount": 0.83,
  "warehouse_id": "1d7029cf-859d-414f-82f8-18f12aa5d8fe",
}, {
  "id": 13,
  "name": "Spice S-5010",
  "category": "laptop",
  "brand": "Canon",
  "price": 106.0,
  "description": "Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.",
  "discount": 0.76,
  "warehouse_id": "8fd82721-c098-4ea3-808d-c58f444ea4b3",
}, {
  "id": 14,
  "name": "Bird S661",
  "category": "memory",
  "brand": "Lenovo",
  "price": 110.88,
  "description": "In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",
  "discount": 0.8,
  "warehouse_id": "64e33796-aa29-498b-b8d8-e4c717737a87",
}, {
  "id": 15,
  "name": "Huawei Ascend G6",
  "category": "projector",
  "brand": "Canon",
  "price": 43.26,
  "description": "Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.",
  "discount": 0.49,
  "warehouse_id": "bec56e9a-75ff-4350-8276-9d8c1ada12b3",
}, {
  "id": 16,
  "name": "Dell Venue 7 8 GB",
  "category": "printer",
  "brand": "Lenovo",
  "price": 70.95,
  "description": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.",
  "discount": 0.54,
  "warehouse_id": "a7c047a6-450d-4075-b168-53eb3032c2c5",
}, {
  "id": 17,
  "name": "Honor 20",
  "category": "desktop",
  "brand": "",
  "price": 60.81,
  "description": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",
  "discount": 0.03,
  "warehouse_id": "cf7535f8-83f9-4f99-9e1d-aecb01967fe3",
}, {
  "id": 18,
  "name": "Spice Smart Pulse (M-9010)",
  "category": "accessories",
  "brand": "Toyota",
  "price": 44.43,
  "description": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.",
  "discount": 0.82,
  "warehouse_id": "61de034d-32dc-434e-a60a-f33b30dc5d72",
}, {
  "id": 19,
  "name": "Nokia 5.3",
  "category": "projector",
  "brand": "Lenovo",
  "price": 60.0,
  "description": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.",
  "discount": 0.85,
  "warehouse_id": "b6e190b8-890a-4fa2-bd2e-e2d141e406c8",
}, {
  "id": 20,
  "name": "Philips X331",
  "category": "projector",
  "brand": "Dell",
  "price": 99.41,
  "description": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.",
  "discount": 0.3,
  "warehouse_id": "106125a9-d507-43b7-91ef-038fbb4fe005",
}, {
  "id": 21,
  "name": "BLU Dash L2",
  "category": "memory",
  "brand": "Lenovo",
  "price": 64.49,
  "description": "Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.",
  "discount": 0.06,
  "warehouse_id": "78f8d817-fa73-4892-b72e-50bb1bc83d10",
}, {
  "id": 22,
  "name": "LG GD550 Pure",
  "category": "memory",
  "brand": "Dell",
  "price": 117.69,
  "description": "Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
  "discount": 0.18,
  "warehouse_id": "11ef91ab-7d18-4e7a-9a78-097fad020837",
}, {
  "id": 23,
  "name": "Samsung T700",
  "category": "laptop",
  "brand": "Toyota",
  "price": 71.47,
  "description": "Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
  "discount": 0.22,
  "warehouse_id": "0e3b9c1a-b934-4ed0-b22b-098f924c3d8d",
}, {
  "id": 24,
  "name": "Huawei Enjoy 6",
  "category": "printer",
  "brand": "Epson",
  "price": 43.92,
  "description": "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
  "discount": 0.73,
  "warehouse_id": "79034cf6-735e-462a-aba9-aa118778fd36",
}, {
  "id": 25,
  "name": "BLU Samba Mini",
  "category": "printer",
  "brand": "Mac",
  "price": 64.69,
  "description": "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.",
  "discount": 0.29,
  "warehouse_id": "6913fe62-25b0-4616-9b84-e820ed02b1f5",
}, {
  "id": 26,
  "name": "BlackBerry Z10",
  "category": "laptop",
  "brand": "Dell",
  "price": 86.86,
  "description": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.",
  "discount": 0.78,
  "warehouse_id": "62b3ec2c-456f-4958-8504-110d68969df1",
}, {
  "id": 27,
  "name": "BLU Studio 7.0 LTE",
  "category": "printer",
  "brand": "Lenovo",
  "price": 68.42,
  "description": "Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.",
  "discount": 0.9,
  "warehouse_id": "9a207cd5-1dd7-47f7-b2db-e3114b09bbf6",
}, {
  "id": 28,
  "name": "LG K41S",
  "category": "laptop",
  "brand": "",
  "price": 99.63,
  "description": "Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.",
  "discount": 0.1,
  "warehouse_id": "027cac93-560d-4efd-9e55-04abace0af9d",
}, {
  "id": 29,
  "name": "Samsung T200",
  "category": "laptop",
  "brand": "Lenovo",
  "price": 88.77,
  "description": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.",
  "discount": 0.98,
  "warehouse_id": "25985f48-aef8-4413-88b0-95ca0dd85861",
}, {
  "id": 30,
  "name": "verykool s470",
  "category": "memory",
  "brand": "MSI",
  "price": 78.46,
  "description": "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.",
  "discount": 0.15,
  "warehouse_id": "b59881ac-eb04-405c-8956-75c3c3e6cae9",
}, {
  "id": 31,
  "name": "LG Harmony",
  "category": "laptop",
  "brand": "Dell",
  "price": 51.36,
  "description": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
  "discount": 0.55,
  "warehouse_id": "8ddb85f0-3fce-43ef-bfdb-f298980f1602",
}, {
  "id": 32,
  "name": "Motorola Moto X Force",
  "category": "memory",
  "brand": "",
  "price": 114.19,
  "description": "Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.",
  "discount": 0.03,
  "warehouse_id": "c0d2d530-62a1-40c6-8d21-61e1b15a160c",
}, {
  "id": 33,
  "name": "Nokia 7020",
  "category": "memory",
  "brand": "Dell",
  "price": 56.26,
  "description": "Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.",
  "discount": 0.84,
  "warehouse_id": "ad8e6172-b424-4e1c-9152-1ab747d1cc40",
}, {
  "id": 34,
  "name": "Haier M2000",
  "category": "memory",
  "brand": "Dell",
  "price": 36.39,
  "description": "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.",
  "discount": 0.78,
  "warehouse_id": "0ea982fa-be3c-4772-bea6-5ef7502d5495",
}, {
  "id": 35,
  "name": "BLU Studio C",
  "category": "memory",
  "brand": "Epson",
  "price": 93.66,
  "description": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
  "discount": 0.57,
  "warehouse_id": "21160c37-a412-49df-819e-42b260b5dbf0",
}, {
  "id": 36,
  "name": "alcatel OT-385",
  "category": "desktop",
  "brand": "Epson",
  "price": 75.53,
  "description": "In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
  "discount": 0.27,
  "warehouse_id": "96551921-1851-4d71-93f2-234f3e774dcd",
}, {
  "id": 37,
  "name": "LG G Pad 8.0",
  "category": "desktop",
  "brand": "Toyota",
  "price": 108.67,
  "description": "Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.",
  "discount": 0.35,
  "warehouse_id": "2fe5f62f-2e75-49ad-bda4-5ac9ac816347",
}, {
  "id": 38,
  "name": "Sony Ericsson C903",
  "category": "laptop",
  "brand": "",
  "price": 64.59,
  "description": "Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
  "discount": 0.93,
  "warehouse_id": "70d92cae-2a8f-4a35-bd9e-cae5bacd816e",
}, {
  "id": 39,
  "name": "Micromax A99 Canvas Xpress",
  "category": "memory",
  "brand": "Lenovo",
  "price": 107.19,
  "description": "Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.",
  "discount": 0.82,
  "warehouse_id": "6e1146d0-492c-4db9-84d5-700a9c3e446f",
}, {
  "id": 40,
  "name": "Honor 10 Lite",
  "category": "projector",
  "brand": "",
  "price": 102.13,
  "description": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.",
  "discount": 0.69,
  "warehouse_id": "24eaa512-1cb1-4689-93e5-49a9ba55b88d",
}, {
  "id": 41,
  "name": "Celkon Q519",
  "category": "memory",
  "brand": "",
  "price": 57.98,
  "description": "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
  "discount": 0.1,
  "warehouse_id": "28c874d4-854b-4291-b2b1-3ac12e227dbf",
}, {
  "id": 42,
  "name": "Sagem my200C",
  "category": "laptop",
  "brand": "Epson",
  "price": 63.48,
  "description": "Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
  "discount": 0.28,
  "warehouse_id": "796fd7bd-d73a-4c85-9285-545cd7e12e54",
}, {
  "id": 43,
  "name": "Sagem my301X",
  "category": "laptop",
  "brand": "Epson",
  "price": 55.38,
  "description": "Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.",
  "discount": 0.39,
  "warehouse_id": "e54b463f-de22-44e1-b437-e95376146c45",
}, {
  "id": 44,
  "name": "ZTE Maven 2",
  "category": "laptop",
  "brand": "Canon",
  "price": 34.78,
  "description": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.",
  "discount": 0.9,
  "warehouse_id": "8eb03963-4a30-4eb4-8367-02e3b63b8a22",
}, {
  "id": 45,
  "name": "Sony Ericsson Xperia active",
  "category": "projector",
  "brand": "MSI",
  "price": 39.92,
  "description": "Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.",
  "discount": 0.55,
  "warehouse_id": "26734314-2db2-4111-97f4-1caf85e054df",
}, {
  "id": 46,
  "name": "Huawei nova 5z",
  "category": "accessories",
  "brand": "Lenovo",
  "price": 68.16,
  "description": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.",
  "discount": 0.98,
  "warehouse_id": "9791f9f3-b8bc-4121-be8c-5c8e6d3420b5",
}, {
  "id": 47,
  "name": "Motorola Motoluxe XT389",
  "category": "projector",
  "brand": "",
  "price": 102.87,
  "description": "Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.",
  "discount": 0.73,
  "warehouse_id": "2852951f-8d72-4f8a-9e09-cdb20e6950f0",
}, {
  "id": 48,
  "name": "Samsung E1085T",
  "category": "projector",
  "brand": "Canon",
  "price": 72.88,
  "description": "Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.",
  "discount": 0.05,
  "warehouse_id": "03991e41-44c7-4f11-a50b-aab486bbb6a2",
}, {
  "id": 49,
  "name": "Motorola A780",
  "category": "desktop",
  "brand": "Canon",
  "price": 88.19,
  "description": "Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
  "discount": 0.99,
  "warehouse_id": "100e0cbc-c866-43c4-9add-8a19306f96cb",
}, {
  "id": 50,
  "name": "O2 XDA Argon",
  "category": "memory",
  "brand": "Dell",
  "price": 101.52,
  "description": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.",
  "discount": 0.45,
  "warehouse_id": "56aa4cf6-c725-491e-8663-78a3b8348408",
}];

