import type { Metadata } from "next";
import { AdminSideBar } from "@/components/share/admin/admin-side-bar";
// import { auth } from "@/auth";
// import { redirect } from "next/navigation";

export const metadata: Metadata = {
    title: "Admin Page",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // const session = await auth();
    // if (!session || session.user.role === "USER") {
    //     redirect("/");
    // }
    return <AdminSideBar>{children}</AdminSideBar>;
}
